### PR TITLE
Introduce the `MandrillEmail` to prevent orphans.

### PR DESCRIPTION
**Pull request by adinapoli**
This commit introduces a newtype wrapper called `MandrillEmail` to wrap
the internal `EmailAddress` and thus avoid the need for a
ToJSON/FromJSON orphan instances.

Despite the newtype introduction the API should not break for the end
user, provided he created the `MandrillRecipient` via the smart
constructor, and he's not poking around with the `MandrillMessage`. We
should probably avoid exporting the entire Types.hs module, but only
types & smart constructors (and lenses!) but that is out of the scope of
this PR.

As low hanging fruit, I have ported the project to stack.

@gregwebs Are you cool with me merging? I will release the new Mandrill
upstream on Hackage soon afterwards.

### CODE REVIEW

**Comment by gregwebs** [comment]
Looks good. You might also want to adjust your lenses to automatically wrap and unwrap the newtype (you should be able to do this by omitting the `_` from the field and then manually writing the lens).

**Comment by adinapoli** [comment]
For now I haven't even bothered to derive lenses for `MandrillEmail`, hoping it will be an ephemeral types the user shouldn't be bothered with, but :+1: for the suggestion! And, as always, feel free to open a PR ;)

I will wait for Travis to validate, then merge.

**Comment by gregwebs** [comment]
Thanks. This is a good solution since it doesn't even expose anything different to the normal use case.

**Comment by adinapoli** [comment]
@gregwebs Pleasure! On Hackage as we speak:

http://hackage.haskell.org/package/mandrill

**Pull request merged**
