### PR TITLE
add webhooks api

### PR DESCRIPTION
**Pull request by mwotton**

### CODE REVIEW

**Comment by adinapoli** [comment]
Hey @mwotton , thank you for yet-another-PR!

This looks great. As a minor nitpick, can I ask you to explicitly import `Control.Applicative.pure` so that the library builds clean on Travis for GHC < 7.10? See here:

https://travis-ci.org/adinapoli/mandrill/jobs/184666259

Thank you!

**Comment by mwotton** [comment]
done! :)

**Comment by adinapoli** [comment]
Thanks!

**Comment by mwotton** [comment]
no worries. ping me on release to hackage?

**Comment by adinapoli** [comment]
No worries, will do! (Will try to  make it  happen  at  the  end  of  today)

**Comment by adinapoli** [comment]
@mwotton on Hackage as we speak! 😉

**Comment by mwotton** [comment]
Cheers mate

**Pull request merged**
